name: Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      site_artifact: ${{ steps.build_site.outputs.name }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup | Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.nixos.org/
            experimental-features = nix-command flakes
      
      - name: Setup | Cachix
        uses: cachix/cachix-action@v10
        with:
          name: niederman
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Build | Generator
        id: build_generator
        run: |
          nix build .#gen
          echo ::set-output name=path::$(readlink ./result)
          echo ::set-output name=name::$(basename $(readlink ./result))
      
      - name: Upload | Generator
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_generator.outputs.name }}
          path: ${{ steps.build_generator.outputs.path }}

      - name: Build | Site
        id: build_site
        run: |
          nix build .#site
          echo ::set-output name=path::$(readlink ./result)
          echo ::set-output name=name::$(basename $(readlink ./result))
      
      - name: Upload | Site
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.build_site.outputs.name }}
          path: ${{ steps.build_site.outputs.path }}
    
  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup | Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.build.outputs.site_artifact }}
          path: _site
      
      - name: Publish | Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: maxniederman
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
